// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Models;

namespace Travel.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20221026183221_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Travel.Models.TravelReview", b =>
                {
                    b.Property<int>("TravelReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewBody")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ReviewTitle")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Reviewer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("TravelReviewId");

                    b.ToTable("TravelReviews");

                    b.HasData(
                        new
                        {
                            TravelReviewId = 1,
                            Location = "Mordor, New Zealand",
                            Rating = 1,
                            ReviewBody = "Mordor is super hot. I wish someone would have warned me before I went on this quest to destroy some random ring.",
                            ReviewTitle = "It's too hot here",
                            Reviewer = "Trevor"
                        },
                        new
                        {
                            TravelReviewId = 2,
                            Location = "The Lonely Mountain",
                            Rating = 3,
                            ReviewBody = "there was a dragon",
                            ReviewTitle = "Beautiful",
                            Reviewer = "KB"
                        },
                        new
                        {
                            TravelReviewId = 3,
                            Location = "The Shire",
                            Rating = 0,
                            ReviewBody = "I didn't realize that the Shire was burning",
                            ReviewTitle = "too many orcs",
                            Reviewer = "KB"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
